// Texto da navegação, por locale.
//
// `categories` é o nome de um agrupamento da sidebar; `nav`, o de um item do
// navbar; `outline`, o título do sumário lateral ("Nesta página"); `pages`, o
// título de uma página, com a rota (sem o prefixo do locale) como chave.
//
// Título que não se traduz — nome de elemento (`Button`) ou de pacote (`dom`) —
// não entra aqui: vive junto da forma, em `sidebar.js`.
const labels = {
  en: {
    nav: {
      manifesto: 'Manifesto',
      about: 'About',
      docs: 'Docs',
      components: 'Components',
    },
    outline: 'On this page',
    categories: {
      learn: 'Learn',
      foundations: 'Foundations',
      designTokens: 'Design tokens',
      buildUi: 'Build UI',
      components: 'Components',
      layout: 'Layout',
      typography: 'Typography',
      forms: 'Forms',
      data: 'Data',
      behavior: 'Behavior',
      makingItYours: 'Making it yours',
      buildElements: 'Build Elements',
    },
    pages: {
      'learn/introduction': 'Introduction',
      'learn/installation': 'Installation',
      'learn/quick-start': 'Quick start',
      'foundations/principles': 'Principles',
      'foundations/naming': 'Naming',
      'foundations/events-and-echo': 'Events and Echo',
      'foundations/tokens/': 'Design tokens',
      'foundations/tokens/colors': 'Colors',
      'foundations/tokens/typography': 'Typography',
      'foundations/tokens/spacing': 'Spacing',
      'foundations/tokens/border': 'Border',
      'foundations/tokens/shadows': 'Shadows',
      'foundations/tokens/opacity': 'Opacity',
      'components/': 'Components',
      'build-ui/forms': 'Forms',
      'build-ui/theming': 'Styling',
      'build-ui/patterns/': 'Cookbook',
      'build-ui/patterns/search-as-you-type': 'Search as you type',
      'build-ui/patterns/user-crud': 'User CRUD',
      'build-ui/patterns/declarative-navigation': 'Declarative navigation',
      'build-elements/': 'Packages',
      'build-elements/lifecycle': 'Lifecycle',
      'build-elements/tools': 'Tools and workflows',
      contributing: 'Contributing',
    },
  },

  'pt-br': {
    nav: {
      manifesto: 'Manifesto',
      about: 'Sobre',
      docs: 'Docs',
      components: 'Componentes',
    },
    outline: 'Nesta página',
    categories: {
      learn: 'Aprender',
      foundations: 'Fundamentos',
      designTokens: 'Design tokens',
      buildUi: 'Construir UI',
      components: 'Componentes',
      layout: 'Layout',
      typography: 'Tipografia',
      forms: 'Formulários',
      data: 'Dados',
      behavior: 'Comportamento',
      makingItYours: 'Personalização',
      buildElements: 'Construir elementos',
    },
    pages: {
      'learn/introduction': 'Introdução',
      'learn/installation': 'Instalação',
      'learn/quick-start': 'Início rápido',
      'foundations/principles': 'Princípios',
      'foundations/naming': 'Nomenclatura',
      'foundations/events-and-echo': 'Eventos e Echo',
      'foundations/tokens/': 'Design tokens',
      'foundations/tokens/colors': 'Cores',
      'foundations/tokens/typography': 'Tipografia',
      'foundations/tokens/spacing': 'Espaçamento',
      'foundations/tokens/border': 'Borda',
      'foundations/tokens/shadows': 'Sombras',
      'foundations/tokens/opacity': 'Opacidade',
      'components/': 'Componentes',
      'build-ui/forms': 'Formulários',
      'build-ui/theming': 'Estilização',
      'build-ui/patterns/': 'Receitas',
      'build-ui/patterns/search-as-you-type': 'Busca enquanto digita',
      'build-ui/patterns/user-crud': 'CRUD de usuários',
      'build-ui/patterns/declarative-navigation': 'Navegação declarativa',
      'build-elements/': 'Pacotes',
      'build-elements/lifecycle': 'Ciclo de vida',
      'build-elements/tools': 'Ferramentas e fluxos de trabalho',
      contributing: 'Contribuir',
    },
  },

  es: {
    nav: {
      manifesto: 'Manifiesto',
      about: 'Acerca de',
      docs: 'Docs',
      components: 'Componentes',
    },
    outline: 'En esta página',
    categories: {
      learn: 'Aprender',
      foundations: 'Fundamentos',
      designTokens: 'Design tokens',
      buildUi: 'Construir UI',
      components: 'Componentes',
      layout: 'Layout',
      typography: 'Tipografía',
      forms: 'Formularios',
      data: 'Datos',
      behavior: 'Comportamiento',
      makingItYours: 'Personalización',
      buildElements: 'Construir elementos',
    },
    pages: {
      'learn/introduction': 'Introducción',
      'learn/installation': 'Instalación',
      'learn/quick-start': 'Inicio rápido',
      'foundations/principles': 'Principios',
      'foundations/naming': 'Nomenclatura',
      'foundations/events-and-echo': 'Eventos y Echo',
      'foundations/tokens/': 'Design tokens',
      'foundations/tokens/colors': 'Colores',
      'foundations/tokens/typography': 'Tipografía',
      'foundations/tokens/spacing': 'Espaciado',
      'foundations/tokens/border': 'Borde',
      'foundations/tokens/shadows': 'Sombras',
      'foundations/tokens/opacity': 'Opacidad',
      'components/': 'Componentes',
      'build-ui/forms': 'Formularios',
      'build-ui/theming': 'Estilos',
      'build-ui/patterns/': 'Recetario',
      'build-ui/patterns/search-as-you-type': 'Búsqueda al escribir',
      'build-ui/patterns/user-crud': 'CRUD de usuarios',
      'build-ui/patterns/declarative-navigation': 'Navegación declarativa',
      'build-elements/': 'Paquetes',
      'build-elements/lifecycle': 'Ciclo de vida',
      'build-elements/tools': 'Herramientas y flujos de trabajo',
      contributing: 'Contribuir',
    },
  },
}

export default labels
